service: auth
frameworkVersion: '2'

custom:
  stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    slim: true
    strip: false
    layer: true
    dockerizePip: non-linux

provider:
  name: aws
  stage: dev
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - sqs:SendMessage
            - sqs:GetQueueUrl
          Resource:
            - Fn::GetAtt:
                - UserQueue
                - Arn
            - Fn::GetAtt:
                - ResetPasswordQueue
                - Arn
            - Fn::GetAtt:
                - ActivationQueue
                - Arn
  environment:
    ENVIRONMENT: ${self:custom.stage}
    DATABASE_URL: ${ssm:/auth/${self:custom.stage}/DATABASE_URL~true}
    SENDGRID_API_KEY: ${ssm:/auth/${self:custom.stage}/SENDGRID_API_KEY~true}
    JWT_SECRET_TOKEN: ${ssm:/auth/${self:custom.stage}/JWT_SECRET_TOKEN~true}
  apiGateway:
    shouldStartNameWithService: true

package:
  exclude:
    - .cache/**
    - .__pycache__/**
    - .git/**
    - .github/**
    - .pytest_cache/**
    - .DS_Store
    - node_modules/**
    - Makefile
    - package-lock.json
    - README.md
    - LICENSE
    - .gitignore
    - tests/**
    - migrations/**
    - pytest.ini

functions:
  sign-up:
    handler: auth/view/function/sign_up.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /sign-up
          method: post
          cors: true
  sign-in:
    handler: auth/view/function/sign_in.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /sign-in
          method: post
          cors: true
  refresh-session:
    handler: auth/view/function/refresh_session.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /refresh-token
          method: post
          cors: true
  sign-out:
    handler: auth/view/function/sign_out.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /sign-out
          method: post
          cors: true
  create-reset-password-token:
    handler: auth/view/function/create_reset_password_token.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /reset-password
          method: post
          cors: true
  reset-password:
    handler: auth/view/function/reset_password.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /reset-password/{reset_password_token}
          method: post
          cors: true
  activate:
    handler: auth/view/function/activate.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /users/activate
          method: post
          cors: true
  profile:
    handler: auth/view/function/profile.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /profile
          method: get
          cors: true
  create-activation:
    handler: auth/view/function/create_activation.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UserQueue
              - Arn
  send-activation-email:
    handler: auth/view/function/send_activation_email.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ActivationQueue
              - Arn
  send-reset-password-email:
    handler: auth/view/function/send_reset_password_email.handle
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ResetPasswordQueue
              - Arn

plugins:
  - serverless-offline
  - serverless-python-requirements

resources:
  Resources:
    UserQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "auth-${self:custom.stage}-user"
    ResetPasswordQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "auth-${self:custom.stage}-reset-password"
    ActivationQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "auth-${self:custom.stage}-activation"
