import os

ENVIRONMENT = os.getenv("ENVIRONMENT", "dev")
DATABASE_URL = os.getenv("DATABASE_URL", "postgres://postgres:@localhost:5432/auth")

TOKEN_EXPIRATION_TIME = os.getenv("TOKEN_EXPIRATION_TIME", 7200)
ACTIVATION_EXPIRE_TIME = 7200
RESET_PASSWORD_TOKEN_EXPIRE_TIME = 7200
JWT_SECRET_TOKEN = os.getenv("JWT_SECRET_TOKEN", "")

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
ACTIVATION_EMAIL_TEMPLATE_ID = "d-3ead08e1fb3b4421918856345cf217f2"
RESET_PASSWORD_EMAIL_TEMPLATE_ID = "d-fbf97fc282a24f99bb63d7045702a3a1"

AUTH_APP_URL_PROD = "https://www.nicolaszein.dev/auth"
AUTH_APP_URL_STAGING = "https://staging.nicolaszein.dev/auth"
AUTH_APP_URL = (
    AUTH_APP_URL_PROD if ENVIRONMENT == "production" else AUTH_APP_URL_STAGING
)

USER_QUEUE = f"auth-{ENVIRONMENT}-user"
RESET_PASSWORD_QUEUE = f"auth-{ENVIRONMENT}-reset-password"
ACTIVATION_QUEUE = f"auth-{ENVIRONMENT}-activation"
