import os

ENVIRONMENT = os.getenv('ENVIRONMENT', 'dev')
DATABASE_URL = os.getenv('DATABASE_URL', 'postgres://postgres:@localhost:5432/auth')

TOKEN_EXPIRATION_TIME = os.getenv('TOKEN_EXPIRATION_TIME', 7200)
ACTIVATION_EXPIRE_TIME = 7200
JWT_SECRET_TOKEN = os.getenv('JWT_SECRET_TOKEN', '')

SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')
ACTIVATION_EMAIL_TEMPLATE_ID = 'd-b9bd881a306543d796601e6bd3586530'

USER_QUEUE = f'auth-{ENVIRONMENT}-user'
