"""add_user_reset_password_token

Revision ID: 52cbe5c5e367
Revises: b8c610a016ea
Create Date: 2021-03-01 01:13:50.373123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cbe5c5e367'
down_revision = 'b8c610a016ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password_token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('reset_password_token_created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_reset_password_token'), 'user', ['reset_password_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_password_token'), table_name='user')
    op.drop_column('user', 'reset_password_token_created_at')
    op.drop_column('user', 'reset_password_token')
    # ### end Alembic commands ###
