"""change_from_is_active_to_status

Revision ID: b8c610a016ea
Revises: cb9aa40c9f79
Create Date: 2021-02-27 00:44:04.138844

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b8c610a016ea'
down_revision = 'cb9aa40c9f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'status',
            sa.String(length=20),
            server_default='inactive',
            nullable=False
        )
    )
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
